#!/usr/bin/env bash

checkDir() {
    if [ ! -d "$1" ]; then
        mkdir -p "$1"
    fi
}

echo "[!] Check the content of this script first before proceeding! CTRL+C to cancel."
read -r -p "    Press ENTER to continue..."

echo "[i] Copying dotfiles..."
checkDir ~/.config  # create .config if it does not exist

echo " + Copying cava dotfiles..."
checkDir ~/.config/cava
cp ./dotfiles/cava/config ~/.config/cava/config

echo " + Copying dunst dotfiles..."
checkDir ~/.config/dunst
cp ./dotfiles/dunst/dunstrc ~/.config/dunst/dunstrc

echo " + Copying hyprland dotfiles..."
rm -r ~/.config/hypr
cp -r ./dotfiles/hypr ~/.config/hypr

echo " + Copying kitty dotfiles..."
rm -r ~/.config/kitty
cp -r ./dotfiles/kitty ~/.config/kitty

echo " + Copying mpd dotfiles..."
# do not delete its directory, it contains the database and other user data
checkDir ~/.config/mpd
cp ./dotfiles/mpd/mpd.conf ~/.config/mpd/mpd.conf

echo " + Copying ncmpcpp dotfiles..."
checkDir ~/.config/ncmpcpp
cp ./dotfiles/ncmpcpp/config ~/.config/ncmpcpp/config

echo " + Copying sddm dotfiles..."
sudo cp ./dotfiles/sddm/sddm.conf /etc/sddm.conf.d/sddm.conf

echo " + Copying swappy dotfiles..."
checkDir ~/.config/swappy
cp ./dotfiles/swappy/config ~/.config/swappy/config

echo " + Copying swaylock dotfiles..."
checkDir ~/.config/swaylock
cp ./dotfiles/swaylock/config ~/.config/swaylock/config

echo " + Copying waybar dotfiles..."
rm -r ~/.config/waybar
cp -r ./dotfiles/waybar ~/.config/waybar

echo " + Copying wlogout dotfiles..."
rm -r ~/.config/wlogout
cp -r ./dotfiles/wlogout ~/.config/wlogout

echo " + Copying wofi dotfiles..."
rm -r ~/.config/wofi
cp -r ./dotfiles/wofi ~/.config/wofi

echo " + Copying zathura dotfiles..."
rm -r ~/.config/zathura
cp -r ./dotfiles/zathura ~/.config/zathura

echo "[i] Copying dotfiles... Done!"

echo "[i] Copying scripts..."
rm -r ~/.config/scripts/
cp -r ./scripts ~/.config/scripts/
echo "[i] Copying scripts... Done!"
